apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
spec:
  dnsNames:
    - {{ args.env_name }}.podtato.{{ base_dns }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  secretName: ingress-cert
