replicas:
  # con't have enough hats in test environments
  hat: 2

# uncomment this to disable legs on test...who needs legs anyway in test envs?
legs_enabled: {{ args.force_legs }}

podinfo:
  color: red

ingress_port: 8080
